### ISSUE TITLE
Documentation is incomplete or there is a bug in authentication for token only users

### ISSUE THREAD

**Issue by StevenWoo** [chat-sdk/docs#1]
(updated to latest sdk)
The steps in the documentation are:

```
AccountDetails details = new AccountDetails.token("Token");
NM.auth().authenticate(details).subscribe();
```

When the second line executes, there is an immediate exception that complains about the token format which is in the documentation but there is no documentation about the token format.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.karmist.austin, PID: 7083
                  io.reactivex.exceptions.OnErrorNotImplementedException: The custom token format is incorrect. Please check the documentation.
                      at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:51)
                      at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
                      at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:96)
                      at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
                      at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
                      at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
                      at co.chatsdk.firebase.FirebaseAuthenticationHandler$6$1.onComplete(FirebaseAuthenticationHandler.java:102)
                      at com.google.android.gms.tasks.zzf.run(Unknown Source)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The custom token format is incorrect. Please check the documentation.
                      at com.google.android.gms.internal.zzdkj.zzak(Unknown Source)
                      at com.google.android.gms.internal.zzdjl.zza(Unknown Source)
                      at com.google.android.gms.internal.zzdku.zzal(Unknown Source)
                      at com.google.android.gms.internal.zzdkw.onFailure(Unknown Source)
                      at com.google.android.gms.internal.zzdkl.onTransact(Unknown Source)
                      at android.os.Binder.execTransact(Binder.java:565)



When one follows the directions for the username/password scenario there is an immediate exception
               AccountDetails details = AccountDetails.username("Joe", "Joe123");
                NM.auth().authenticate(details).subscribe();
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.karmist.austin, PID: 2130
                  io.reactivex.exceptions.OnErrorNotImplementedException: The email address is badly formatted.
                      at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:51)
                      at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
                      at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:96)
                      at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
                      at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
                      at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
                      at co.chatsdk.firebase.FirebaseAuthenticationHandler$6$1.onComplete(FirebaseAuthenticationHandler.java:102)
                      at com.google.android.gms.tasks.zzf.run(Unknown Source)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The email address is badly formatted.
                      at com.google.android.gms.internal.zzdkj.zzak(Unknown Source)
                      at com.google.android.gms.internal.zzdjl.zza(Unknown Source)
                      at com.google.android.gms.internal.zzdku.zzal(Unknown Source)
                      at com.google.android.gms.internal.zzdkw.onFailure(Unknown Source)
                      at com.google.android.gms.internal.zzdkl.onTransact(Unknown Source)
                      at android.os.Binder.execTransact(Binder.java:565)
```

Is there a step missing or could I possibly have misconfigured something?  Neither user in the above cases shows up in firebase.

when I try signup

```
  AccountDetails details = AccountDetails.signUp("Joe", "Joe123");
                NM.auth().authenticate(details).subscribe();
```

there is an email exception

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.karmist.austin, PID: 5129
                  io.reactivex.exceptions.OnErrorNotImplementedException: The email address is badly formatted.
                      at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:51)
                      at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
                      at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:96)
                      at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
                      at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
                      at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
                      at co.chatsdk.firebase.FirebaseAuthenticationHandler$6$1.onComplete(FirebaseAuthenticationHandler.java:102)
                      at com.google.android.gms.tasks.zzf.run(Unknown Source)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The email address is badly formatted.
                      at com.google.android.gms.internal.zzdkj.zzak(Unknown Source)
                      at com.google.android.gms.internal.zzdjl.zza(Unknown Source)
                      at com.google.android.gms.internal.zzdku.zzal(Unknown Source)
                      at com.google.android.gms.internal.zzdkw.onFailure(Unknown Source)
                      at com.google.android.gms.internal.zzdkl.onTransact(Unknown Source)
                      at android.os.Binder.execTransact(Binder.java:565)
```

**Comment by bensmiley** [comment]
In the documentation, this is meant to be an example - not used literally. For example `Token` isn't a valid token. You should substitute your own valid token using [these instructions](https://github.com/chat-sdk/docs#generating-the-token).

Similarly, with username / password login, the values provided in the guide are just examples, in reality, your user would be providing a real email address and password. There are two things to note:

1. The first time new credentials are provided it would be necessary to register in stead of trying to authenticate. 

2. Firebase require the username to be a valid email address. 

I've updated the documentation to make it more clear.

**Comment by ganico** [comment]
![Screen Shot 2020-03-05 at 23 36 00](https://user-images.githubusercontent.com/7714293/75997662-a3daf880-5f3a-11ea-9881-46ae9db228e2.png)

Im currently implementing it on swift, but it seems not to work... can you confirm if I missed something? @bensmiley thank you
